{% set name = "pygtc" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyGTC-{{ version }}.tar.gz
  sha256: 179dd20e99142bb2f351c64d2a5b0a4c9d5e6245c746888cd406e1c0aaf79400

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base >=2.2.0
    - numpy >=1.7.1
    - packaging
    - python >=2.7,<3.0|>=3.6,<4.0

test:
  imports:
    - pygtc
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sebastianbocquet/pygtc
  summary: Make an awesome giant triangle confusogram (gtc)!
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - FaustinCarter
    - SebastianBocquet
